class GetmeetingListEntity {
	int code;
	GetmeetingListData data;
	String message;

	GetmeetingListEntity({this.code, this.data, this.message});

	GetmeetingListEntity.fromJson(Map<String, dynamic> json) {
		code = json['code'];
		data = json['data'] != null ? new GetmeetingListData.fromJson(json['data']) : null;
		message = json['message'];
	}

	Map<String, dynamic> toJson() {
		final Map<String, dynamic> data = new Map<String, dynamic>();
		data['code'] = this.code;
		if (this.data != null) {
      data['data'] = this.data.toJson();
    }
		data['message'] = this.message;
		return data;
	}
}

class GetmeetingListData {
	int thisPageFirstElementNumber;
	int curPage;
	int previousPage;
	int thisPageLastElementNumber;
	bool firstPage;
	bool lastPage;
	int nextPage;
	List<GetmeetingListDataElemants> elements;
	int pageSize;
	int lastPageNumber;
	int totalElements;

	GetmeetingListData({this.thisPageFirstElementNumber, this.curPage, this.previousPage, this.thisPageLastElementNumber, this.firstPage, this.lastPage, this.nextPage, this.elements, this.pageSize, this.lastPageNumber, this.totalElements});

	GetmeetingListData.fromJson(Map<String, dynamic> json) {
		thisPageFirstElementNumber = json['thisPageFirstElementNumber'];
		curPage = json['curPage'];
		previousPage = json['previousPage'];
		thisPageLastElementNumber = json['thisPageLastElementNumber'];
		firstPage = json['firstPage'];
		lastPage = json['lastPage'];
		nextPage = json['nextPage'];
		if (json['elements'] != null) {
			elements = new List<GetmeetingListDataElemants>();(json['elements'] as List).forEach((v) { elements.add(new GetmeetingListDataElemants.fromJson(v)); });
		}
		pageSize = json['pageSize'];
		lastPageNumber = json['lastPageNumber'];
		totalElements = json['totalElements'];
	}

	Map<String, dynamic> toJson() {
		final Map<String, dynamic> data = new Map<String, dynamic>();
		data['thisPageFirstElementNumber'] = this.thisPageFirstElementNumber;
		data['curPage'] = this.curPage;
		data['previousPage'] = this.previousPage;
		data['thisPageLastElementNumber'] = this.thisPageLastElementNumber;
		data['firstPage'] = this.firstPage;
		data['lastPage'] = this.lastPage;
		data['nextPage'] = this.nextPage;
		if (this.elements != null) {
      data['elements'] =  this.elements.map((v) => v.toJson()).toList();
    }
		data['pageSize'] = this.pageSize;
		data['lastPageNumber'] = this.lastPageNumber;
		data['totalElements'] = this.totalElements;
		return data;
	}
}

class GetmeetingListDataElemants {
	String fromPlatName;
	String userDynamicList;
	String meetingStatus;
	String usherRobots;
	String companyName;
	String meetingIcon;
	int mtlCount;
	int meetingId;
	int type;
	int flagReason;
	int checkin;
	int province;
	String systemName;
	String areaName;
	String meetingNoticeList;
	String emceeRobots;
	int smsNum;
	String feeTypeName;
	int feeType;
	String feeTypeBakName;
	int minNum;
	String meetingName;
	String vzhMeetingName;
	String flagStatus;
	int fromPlat;
	int isApplyPoints;
	bool invEnable;
	String saleUserName;
	int unreadNum;
	String provinceName;
	String vvPicTitle;
	int saleUserId;
	String pointStatusName;
	String vvGroupUrl;
	int status;
	String signInQrCode;
	String perfectStatus;
	int flag;
	int city;
	String sponsorName;
	String typeName;
	String vipReceiveUser;
	String templateCode;
	int publishFlag;
	double otherPrice;
	String preTimeStr;
	int startTime;
	double meetingIncome;
	int systemId;
	int ticketCount;
	int isVzh;
	String vvBgPic;
	String invQrCode;
	String vvCount;
	int foodUserCount;
	int feeTypeBak;
	double expectPrice;
	int createOn;
	String vvGroupQrCode;
	String contactUser;
	int endTime;
	String signUpMsg;
	String infos;
	String autoDayTime;
	int hostUserId;
	String contactInfo;
	String cancelStatus;
	String createOnStr;
	int estimateNum;
	String invPicTitle;
	String pointRemark;
	int roomNum;
	String salesUserMobile;
	int pointStatus;
	int actualNum;
	int area;
	String contactMobile;
	String flagReasonName;
	double roomPrice;
	String serialNumber;
	int vzhStatus;
	int followStatus;
	String weChatUrl;
	String eoUrl;
	String activityAddr;
	bool vvGroupEnable;
	String vipGuestList;
	double roomIncome;
	int controlUserCount;
	String serviceBags;
	String meetingTypeName;
	String startTimeStr;
	int point;
	String invUrl;
	int total;
	String cityName;
	int isImportant;
	String serviceBagStr;
	String passed;
	double serveMoney;
	String robotBags;
	String invBgPic;
	String isPay;
	double foodIncome;
	int verified;
	String preTime;
	String mtlList;
	String meetingIntro;
	String templateUrl;
	String meetingAddress;
	String hostUserName;
	String endTimeStr;
	int meetingAddressId;
	String isVzhStatus;
	String mark;

	GetmeetingListDataElemants({this.fromPlatName, this.userDynamicList, this.meetingStatus, this.usherRobots, this.companyName, this.meetingIcon, this.mtlCount, this.meetingId, this.type, this.flagReason, this.checkin, this.province, this.systemName, this.areaName, this.meetingNoticeList, this.emceeRobots, this.smsNum, this.feeTypeName, this.feeType, this.feeTypeBakName, this.minNum, this.meetingName, this.vzhMeetingName, this.flagStatus, this.fromPlat, this.isApplyPoints, this.invEnable, this.saleUserName, this.unreadNum, this.provinceName, this.vvPicTitle, this.saleUserId, this.pointStatusName, this.vvGroupUrl, this.status, this.signInQrCode, this.perfectStatus, this.flag, this.city, this.sponsorName, this.typeName, this.vipReceiveUser, this.templateCode, this.publishFlag, this.otherPrice, this.preTimeStr, this.startTime, this.meetingIncome, this.systemId, this.ticketCount, this.isVzh, this.vvBgPic, this.invQrCode, this.vvCount, this.foodUserCount, this.feeTypeBak, this.expectPrice, this.createOn, this.vvGroupQrCode, this.contactUser, this.endTime, this.signUpMsg, this.infos, this.autoDayTime, this.hostUserId, this.contactInfo, this.cancelStatus, this.createOnStr, this.estimateNum, this.invPicTitle, this.pointRemark, this.roomNum, this.salesUserMobile, this.pointStatus, this.actualNum, this.area, this.contactMobile, this.flagReasonName, this.roomPrice, this.serialNumber, this.vzhStatus, this.followStatus, this.weChatUrl, this.eoUrl, this.activityAddr, this.vvGroupEnable, this.vipGuestList, this.roomIncome, this.controlUserCount, this.serviceBags, this.meetingTypeName, this.startTimeStr, this.point, this.invUrl, this.total, this.cityName, this.isImportant, this.serviceBagStr, this.passed, this.serveMoney, this.robotBags, this.invBgPic, this.isPay, this.foodIncome, this.verified, this.preTime, this.mtlList, this.meetingIntro, this.templateUrl, this.meetingAddress, this.hostUserName, this.endTimeStr, this.meetingAddressId, this.isVzhStatus, this.mark});

	GetmeetingListDataElemants.fromJson(Map<String, dynamic> json) {
		fromPlatName = json['fromPlatName'];
		userDynamicList = json['userDynamicList'];
		meetingStatus = json['meetingStatus'];
		usherRobots = json['usherRobots'];
		companyName = json['companyName'];
		meetingIcon = json['meetingIcon'];
		mtlCount = json['mtlCount'];
		meetingId = json['meetingId'];
		type = json['type'];
		flagReason = json['flagReason'];
		checkin = json['checkin'];
		province = json['province'];
		systemName = json['systemName'];
		areaName = json['areaName'];
		meetingNoticeList = json['meetingNoticeList'];
		emceeRobots = json['emceeRobots'];
		smsNum = json['smsNum'];
		feeTypeName = json['feeTypeName'];
		feeType = json['feeType'];
		feeTypeBakName = json['feeTypeBakName'];
		minNum = json['minNum'];
		meetingName = json['meetingName'];
		vzhMeetingName = json['vzhMeetingName'];
		flagStatus = json['flagStatus'];
		fromPlat = json['fromPlat'];
		isApplyPoints = json['isApplyPoints'];
		invEnable = json['invEnable'];
		saleUserName = json['saleUserName'];
		unreadNum = json['unreadNum'];
		provinceName = json['provinceName'];
		vvPicTitle = json['vvPicTitle'];
		saleUserId = json['saleUserId'];
		pointStatusName = json['pointStatusName'];
		vvGroupUrl = json['vvGroupUrl'];
		status = json['status'];
		signInQrCode = json['signInQrCode'];
		perfectStatus = json['perfectStatus'];
		flag = json['flag'];
		city = json['city'];
		sponsorName = json['sponsorName'];
		typeName = json['typeName'];
		vipReceiveUser = json['vipReceiveUser'];
		templateCode = json['templateCode'];
		publishFlag = json['publishFlag'];
		otherPrice = json['otherPrice'];
		preTimeStr = json['preTimeStr'];
		startTime = json['startTime'];
		meetingIncome = json['meetingIncome'];
		systemId = json['systemId'];
		ticketCount = json['ticketCount'];
		isVzh = json['isVzh'];
		vvBgPic = json['vvBgPic'];
		invQrCode = json['invQrCode'];
		vvCount = json['vvCount'];
		foodUserCount = json['foodUserCount'];
		feeTypeBak = json['feeTypeBak'];
		expectPrice = json['expectPrice'];
		createOn = json['createOn'];
		vvGroupQrCode = json['vvGroupQrCode'];
		contactUser = json['contactUser'];
		endTime = json['endTime'];
		signUpMsg = json['signUpMsg'];
		infos = json['infos'];
		autoDayTime = json['autoDayTime'];
		hostUserId = json['hostUserId'];
		contactInfo = json['contactInfo'];
		cancelStatus = json['cancelStatus'];
		createOnStr = json['createOnStr'];
		estimateNum = json['estimateNum'];
		invPicTitle = json['invPicTitle'];
		pointRemark = json['pointRemark'];
		roomNum = json['roomNum'];
		salesUserMobile = json['salesUserMobile'];
		pointStatus = json['pointStatus'];
		actualNum = json['actualNum'];
		area = json['area'];
		contactMobile = json['contactMobile'];
		flagReasonName = json['flagReasonName'];
		roomPrice = json['roomPrice'];
		serialNumber = json['serialNumber'];
		vzhStatus = json['vzhStatus'];
		followStatus = json['followStatus'];
		weChatUrl = json['weChatUrl'];
		eoUrl = json['eoUrl'];
		activityAddr = json['activityAddr'];
		vvGroupEnable = json['vvGroupEnable'];
		vipGuestList = json['vipGuestList'];
		roomIncome = json['roomIncome'];
		controlUserCount = json['controlUserCount'];
		serviceBags = json['serviceBags'];
		meetingTypeName = json['meetingTypeName'];
		startTimeStr = json['startTimeStr'];
		point = json['point'];
		invUrl = json['invUrl'];
		total = json['total'];
		cityName = json['cityName'];
		isImportant = json['isImportant'];
		serviceBagStr = json['serviceBagStr'];
		passed = json['passed'];
		serveMoney = json['serveMoney'];
		robotBags = json['robotBags'];
		invBgPic = json['invBgPic'];
		isPay = json['isPay'];
		foodIncome = json['foodIncome'];
		verified = json['verified'];
		preTime = json['preTime'];
		mtlList = json['mtlList'];
		meetingIntro = json['meetingIntro'];
		templateUrl = json['templateUrl'];
		meetingAddress = json['meetingAddress'];
		hostUserName = json['hostUserName'];
		endTimeStr = json['endTimeStr'];
		meetingAddressId = json['meetingAddressId'];
		isVzhStatus = json['isVzhStatus'];
		mark = json['mark'];
	}

	Map<String, dynamic> toJson() {
		final Map<String, dynamic> data = new Map<String, dynamic>();
		data['fromPlatName'] = this.fromPlatName;
		data['userDynamicList'] = this.userDynamicList;
		data['meetingStatus'] = this.meetingStatus;
		data['usherRobots'] = this.usherRobots;
		data['companyName'] = this.companyName;
		data['meetingIcon'] = this.meetingIcon;
		data['mtlCount'] = this.mtlCount;
		data['meetingId'] = this.meetingId;
		data['type'] = this.type;
		data['flagReason'] = this.flagReason;
		data['checkin'] = this.checkin;
		data['province'] = this.province;
		data['systemName'] = this.systemName;
		data['areaName'] = this.areaName;
		data['meetingNoticeList'] = this.meetingNoticeList;
		data['emceeRobots'] = this.emceeRobots;
		data['smsNum'] = this.smsNum;
		data['feeTypeName'] = this.feeTypeName;
		data['feeType'] = this.feeType;
		data['feeTypeBakName'] = this.feeTypeBakName;
		data['minNum'] = this.minNum;
		data['meetingName'] = this.meetingName;
		data['vzhMeetingName'] = this.vzhMeetingName;
		data['flagStatus'] = this.flagStatus;
		data['fromPlat'] = this.fromPlat;
		data['isApplyPoints'] = this.isApplyPoints;
		data['invEnable'] = this.invEnable;
		data['saleUserName'] = this.saleUserName;
		data['unreadNum'] = this.unreadNum;
		data['provinceName'] = this.provinceName;
		data['vvPicTitle'] = this.vvPicTitle;
		data['saleUserId'] = this.saleUserId;
		data['pointStatusName'] = this.pointStatusName;
		data['vvGroupUrl'] = this.vvGroupUrl;
		data['status'] = this.status;
		data['signInQrCode'] = this.signInQrCode;
		data['perfectStatus'] = this.perfectStatus;
		data['flag'] = this.flag;
		data['city'] = this.city;
		data['sponsorName'] = this.sponsorName;
		data['typeName'] = this.typeName;
		data['vipReceiveUser'] = this.vipReceiveUser;
		data['templateCode'] = this.templateCode;
		data['publishFlag'] = this.publishFlag;
		data['otherPrice'] = this.otherPrice;
		data['preTimeStr'] = this.preTimeStr;
		data['startTime'] = this.startTime;
		data['meetingIncome'] = this.meetingIncome;
		data['systemId'] = this.systemId;
		data['ticketCount'] = this.ticketCount;
		data['isVzh'] = this.isVzh;
		data['vvBgPic'] = this.vvBgPic;
		data['invQrCode'] = this.invQrCode;
		data['vvCount'] = this.vvCount;
		data['foodUserCount'] = this.foodUserCount;
		data['feeTypeBak'] = this.feeTypeBak;
		data['expectPrice'] = this.expectPrice;
		data['createOn'] = this.createOn;
		data['vvGroupQrCode'] = this.vvGroupQrCode;
		data['contactUser'] = this.contactUser;
		data['endTime'] = this.endTime;
		data['signUpMsg'] = this.signUpMsg;
		data['infos'] = this.infos;
		data['autoDayTime'] = this.autoDayTime;
		data['hostUserId'] = this.hostUserId;
		data['contactInfo'] = this.contactInfo;
		data['cancelStatus'] = this.cancelStatus;
		data['createOnStr'] = this.createOnStr;
		data['estimateNum'] = this.estimateNum;
		data['invPicTitle'] = this.invPicTitle;
		data['pointRemark'] = this.pointRemark;
		data['roomNum'] = this.roomNum;
		data['salesUserMobile'] = this.salesUserMobile;
		data['pointStatus'] = this.pointStatus;
		data['actualNum'] = this.actualNum;
		data['area'] = this.area;
		data['contactMobile'] = this.contactMobile;
		data['flagReasonName'] = this.flagReasonName;
		data['roomPrice'] = this.roomPrice;
		data['serialNumber'] = this.serialNumber;
		data['vzhStatus'] = this.vzhStatus;
		data['followStatus'] = this.followStatus;
		data['weChatUrl'] = this.weChatUrl;
		data['eoUrl'] = this.eoUrl;
		data['activityAddr'] = this.activityAddr;
		data['vvGroupEnable'] = this.vvGroupEnable;
		data['vipGuestList'] = this.vipGuestList;
		data['roomIncome'] = this.roomIncome;
		data['controlUserCount'] = this.controlUserCount;
		data['serviceBags'] = this.serviceBags;
		data['meetingTypeName'] = this.meetingTypeName;
		data['startTimeStr'] = this.startTimeStr;
		data['point'] = this.point;
		data['invUrl'] = this.invUrl;
		data['total'] = this.total;
		data['cityName'] = this.cityName;
		data['isImportant'] = this.isImportant;
		data['serviceBagStr'] = this.serviceBagStr;
		data['passed'] = this.passed;
		data['serveMoney'] = this.serveMoney;
		data['robotBags'] = this.robotBags;
		data['invBgPic'] = this.invBgPic;
		data['isPay'] = this.isPay;
		data['foodIncome'] = this.foodIncome;
		data['verified'] = this.verified;
		data['preTime'] = this.preTime;
		data['mtlList'] = this.mtlList;
		data['meetingIntro'] = this.meetingIntro;
		data['templateUrl'] = this.templateUrl;
		data['meetingAddress'] = this.meetingAddress;
		data['hostUserName'] = this.hostUserName;
		data['endTimeStr'] = this.endTimeStr;
		data['meetingAddressId'] = this.meetingAddressId;
		data['isVzhStatus'] = this.isVzhStatus;
		data['mark'] = this.mark;
		return data;
	}
}
